// <auto-generated />
namespace TalentFactory_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TFContextUpdate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TFContextUpdate2));
        
        string IMigrationMetadata.Id
        {
            get { return "201406041248318_TFContextUpdate2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
